### ISSUE TITLE
Question about parameter 

### ISSUE THREAD

**Issue by ZZX-11** [zemingd/Mixup4Code#1]
Dear Authors：
Thank you for your excellent work. It seems there might be an important parameter, **runs**, missing in your code. If you could provide more details or share the relevant code snippet related to this parameter, I would greatly appreciate it.
![image](https://github.com/zemingd/Mixup4Code/assets/113749872/7712f69b-b9d7-4e1b-84ff-fae7e88581ff)
![image](https://github.com/zemingd/Mixup4Code/assets/113749872/3adb8059-d89f-448e-96f7-d087819c5198)

**Comment by zemingd** [comment]
Hi, thank you for your interest in our work. We recommend using the smaller alpha (e.g., 0.1 and 0.05), and the setting of _runs_ depends on your augmentation scale, but in our experiments, we set the _runs_ to 10.

If you have further questions about MixCode or our research work, please feel free to ask.
