### ISSUE TITLE
About source code of KBS2024 

### ISSUE THREAD

**Issue by KarenaQi** [zemingd/Mixup4Code#2]
Could please provide the code of On the effectiveness of graph data augmentation for source code learning?  I want to learn more about how to drop the node and edge, etc. Thank you so much!

**Comment by zemingd** [comment]
Please refer to the [PyG project](https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html#torch_geometric.utils.dropout_edge) (e.g., DropNode and DropEdge) for more details.

**Comment by KarenaQi** [comment]
Could you please provide the whole code of this paper? Thanks so much /(ㄒoㄒ)/~~

**Comment by KarenaQi** [comment]
Hi, could u please the whold code about this paper through this email, thanks a lot
&nbsp;


薛琦
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月18日(星期四) 下午3:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zemingd/Mixup4Code] About source code of KBS2024  (Issue #2)














 
Closed #2 as completed.
